// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LoanUIClient is the client API for LoanUI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LoanUIClient interface {
	// ListEngineSpecs returns a list of Loan Engine(s) that can be started through the UI.
	ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (LoanUI_ListEngineSpecsClient, error)
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error)
}

type loanUIClient struct {
	cc grpc.ClientConnInterface
}

func NewLoanUIClient(cc grpc.ClientConnInterface) LoanUIClient {
	return &loanUIClient{cc}
}

func (c *loanUIClient) ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (LoanUI_ListEngineSpecsClient, error) {
	stream, err := c.cc.NewStream(ctx, &LoanUI_ServiceDesc.Streams[0], "/v1.LoanUI/ListEngineSpecs", opts...)
	if err != nil {
		return nil, err
	}
	x := &loanUIListEngineSpecsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type LoanUI_ListEngineSpecsClient interface {
	Recv() (*ListEngineSpecsResponse, error)
	grpc.ClientStream
}

type loanUIListEngineSpecsClient struct {
	grpc.ClientStream
}

func (x *loanUIListEngineSpecsClient) Recv() (*ListEngineSpecsResponse, error) {
	m := new(ListEngineSpecsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *loanUIClient) IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error) {
	out := new(IsReadOnlyResponse)
	err := c.cc.Invoke(ctx, "/v1.LoanUI/IsReadOnly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LoanUIServer is the server API for LoanUI service.
// All implementations must embed UnimplementedLoanUIServer
// for forward compatibility
type LoanUIServer interface {
	// ListEngineSpecs returns a list of Loan Engine(s) that can be started through the UI.
	ListEngineSpecs(*ListEngineSpecsRequest, LoanUI_ListEngineSpecsServer) error
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error)
	mustEmbedUnimplementedLoanUIServer()
}

// UnimplementedLoanUIServer must be embedded to have forward compatible implementations.
type UnimplementedLoanUIServer struct {
}

func (UnimplementedLoanUIServer) ListEngineSpecs(*ListEngineSpecsRequest, LoanUI_ListEngineSpecsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListEngineSpecs not implemented")
}
func (UnimplementedLoanUIServer) IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReadOnly not implemented")
}
func (UnimplementedLoanUIServer) mustEmbedUnimplementedLoanUIServer() {}

// UnsafeLoanUIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LoanUIServer will
// result in compilation errors.
type UnsafeLoanUIServer interface {
	mustEmbedUnimplementedLoanUIServer()
}

func RegisterLoanUIServer(s grpc.ServiceRegistrar, srv LoanUIServer) {
	s.RegisterService(&LoanUI_ServiceDesc, srv)
}

func _LoanUI_ListEngineSpecs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListEngineSpecsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LoanUIServer).ListEngineSpecs(m, &loanUIListEngineSpecsServer{stream})
}

type LoanUI_ListEngineSpecsServer interface {
	Send(*ListEngineSpecsResponse) error
	grpc.ServerStream
}

type loanUIListEngineSpecsServer struct {
	grpc.ServerStream
}

func (x *loanUIListEngineSpecsServer) Send(m *ListEngineSpecsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _LoanUI_IsReadOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsReadOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoanUIServer).IsReadOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.LoanUI/IsReadOnly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoanUIServer).IsReadOnly(ctx, req.(*IsReadOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LoanUI_ServiceDesc is the grpc.ServiceDesc for LoanUI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LoanUI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.LoanUI",
	HandlerType: (*LoanUIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsReadOnly",
			Handler:    _LoanUI_IsReadOnly_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListEngineSpecs",
			Handler:       _LoanUI_ListEngineSpecs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "loan-ui.proto",
}
